spring:
  application:
    name: employee

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=Asia/Kuala_Lumpur&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariLibraryPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      auto-commit: true
      read-only: false

  cache:
    type: none

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

app:
  import:
    input-directory: /Users/mdtofazzalhossain/Documents/Development/POCProjects/Spring Batch/data/import/
    scheduler:
      delay: 30000